#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api.verify:
  path:     /api/v1/verifications
  controller: App\Infrastructure\Ui\Api\VerificationController::verify
  methods: ['POST']

api.check_verification:
  path:     /api/v1/verifications/{verificationId}
  controller: App\Infrastructure\Ui\Api\VerificationController::check
  methods: ['POST']
